# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to=None)),
                ('birthday', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('picture', models.ImageField(upload_to=None)),
                ('hobbies', models.CharField(max_length=1000)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Human')),
            ],
        ),
    ]
