# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 08:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='avatar',
            field=models.ImageField(default='', upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='birthday',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.PositiveSmallIntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='hobbies',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='human',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.Human'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='nickname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='picture',
            field=models.ImageField(default='', upload_to=None),
            preserve_default=False,
        ),
    ]
