# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160617_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='birthday',
            field=models.DateField(default='01-01-2001'),
        ),
    ]
