# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20160617_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='birthday',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
